//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedidos
    {
        public int codigo { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<int> codigoProduto { get; set; }
        public Nullable<int> qtde { get; set; }
        public Nullable<decimal> valortotal { get; set; }
    
        public virtual produtos produtos { get; set; }
    }
}
